# Generated by Django 3.1.3 on 2021-07-03 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_talento_humano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talento_Humano',
            fields=[
                ('imagen_th', models.ImageField(null=True, upload_to='images/talento_humano')),
                ('cedula_th', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cedula')),
                ('nombres_th', models.CharField(max_length=25, verbose_name='Nombres')),
                ('apellidos_th', models.CharField(max_length=25, verbose_name='Apellidos')),
                ('email_est', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefono_est', models.CharField(max_length=10)),
                ('cargo_th', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Curso')),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.direccion', verbose_name='Dirección')),
            ],
        ),
    ]
