# Generated by Django 3.1.3 on 2021-07-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_talento_humano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estudiante',
            field=models.ManyToManyField(to='app.Estudiante'),
        ),
    ]
