# Generated by Django 3.1.3 on 2021-07-17 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210709_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='id_fichsal',
        ),
        migrations.AddField(
            model_name='ficha_salud',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.estudiante'),
            preserve_default=False,
        ),
    ]
