# Generated by Django 3.1.3 on 2021-07-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210717_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha_salud',
            old_name='estudiante',
            new_name='id_est',
        ),
    ]
