# Generated by Django 3.1.3 on 2021-07-17 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210717_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha_salud',
            name='id_est',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id_fichsal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ficha_salud'),
            preserve_default=False,
        ),
    ]
