# Generated by Django 3.1.3 on 2021-07-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210717_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='estado',
            field=models.BooleanField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notas',
            name='promedio',
            field=models.FloatField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notas',
            name='sumatoria',
            field=models.FloatField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
