# Generated by Django 3.1.3 on 2021-07-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210718_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='nombre_curso',
            field=models.CharField(max_length=25),
        ),
    ]
