# Generated by Django 3.1.3 on 2021-07-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210723_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='id_rep',
            field=models.PositiveIntegerField(editable=False, verbose_name='Nombre del representante'),
        ),
    ]
