# Generated by Django 3.1.3 on 2021-07-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210723_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='id_rep',
            field=models.PositiveIntegerField(verbose_name='Nombre del representante'),
        ),
    ]
