# Generated by Django 3.1.3 on 2021-07-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210723_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='id_rep',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
