# Generated by Django 3.1.3 on 2021-07-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('1', 'Asistente'), ('2', 'Docente'), ('3', 'Representante')], max_length=2, null=True),
        ),
    ]
