# Generated by Django 3.1.3 on 2021-07-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
